#!/bin/sh

set -eu

mkdir -p /var/www/html/storage/app/public /var/www/html/storage/database
chown -R app:app /var/www/html/storage/app/public /var/www/html/storage/database

su-exec app php artisan optimize

exec su-exec app "$@"
